### ISSUE TITLE
Shooting skill

### ISSUE THREAD

**Issue by flitzx** [Kingsage311/qb-skillz#1]
Me and my players do not gaining shooting skill as long as we do not lower Citizen.Wait(25000) at line 25 in clint/main.lua to significantly lower value

**Comment by Kingsage311** [comment]
So it doesn't update every time you shoot it checks every 2 1/2 seconds if you are and if you are then it updates

**Comment by flitzx** [comment]
We have tested with several different weapons and not made it work, but we will test further and see if we can figure out why :)

**Comment by Kingsage311** [comment]
Try a lmg and just automatically fire it

**Comment by flitzx** [comment]
It still does not work but as you can see in the video, but other skills work for us
[https://vimeo.com/700588880](url)

**Comment by Kingsage311** [comment]
Confirmed bug looking for a fix now

**Comment by Kingsage311** [comment]
To be honest, the only way to fix this is to have the entire thread run faster but that massively impacts the performance of the script so my thought process is just to put an export in the hud where you gain stress from shooting this solves a lot of issues because how the code is currently even if you have a jerry can or a blacklisted weapon it will increase shooting skill but qb-hud already has checks for this so it will just be easier to do it from there to do this all you would have to do is look for "shooting" in the client.lua of qb-hud and put this 
`exports["qb-skillz"]:UpdateSkill("Shooting", 0.2)` the line right under the stress trigger

**Comment by Kingsage311** [comment]
Let me know if this fixes your issue
